const heroes = [
    { name: "Alchemist", img: "img/heroes/alchemist.png", rol: "Carry", complejidad: 1, atributo: "fuerza" },
    { name: "Axe", img: "img/heroes/axe.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "fuerza", combo: "stun en area, reduccion de armadura" }, 
    { name: "Bristleback", img: "img/heroes/bristleback.png", rol: "Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Centaur Warrunner", img: "img/heroes/centaur.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Chaos Knight", img: "img/heroes/chaos_knight.png", rol: "Carry, Tanque", complejidad: 2, atributo: "fuerza", combo: "copias, stun" },
    { name: "Dawnbreaker", img: "img/heroes/dawnbreaker.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Doom", img: "img/heroes/doom_bringer.png", rol: "Iniciador, Tanque", complejidad: 3, atributo: "fuerza" },
    { name: "Dragon Knight", img: "img/heroes/dragon_knight.png", rol: "Tanque, Mid", complejidad: 1, atributo: "fuerza" },
    { name: "Earth Spirit", img: "img/heroes/earth_spirit.png", rol: "Iniciador", complejidad: 3, atributo: "fuerza" },
    { name: "Earthshaker", img: "img/heroes/earthshaker.png", rol: "Iniciador", complejidad: 2, atributo: "fuerza" },
    { name: "Elder Titan", img: "img/heroes/elder_titan.png", rol: "Iniciador", complejidad: 3, atributo: "fuerza" },
    { name: "Huskar", img: "img/heroes/huskar.png", rol: "Mid, Iniciador", complejidad: 2, atributo: "fuerza" },
    { name: "Kunkka", img: "img/heroes/kunkka.png", rol: "Iniciador, Mid, Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Legion Commander", img: "img/heroes/legion_commander.png", rol: "Iniciador, Mid", complejidad: 1, atributo: "fuerza" },
    { name: "Lifestealer", img: "img/heroes/life_stealer.png", rol: "Carry", complejidad: 2, atributo: "fuerza" },
    { name: "Mars", img: "img/heroes/mars.png", rol: "Iniciador, Tanque, Mid", complejidad: 2, atributo: "fuerza" },
    { name: "Night Stalker", img: "img/heroes/night_stalker.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Ogre Magi", img: "img/heroes/ogre_magi.png", rol: "Support, Iniciador", complejidad: 1, atributo: "fuerza" },
    { name: "Omniknight", img: "img/heroes/omniknight.png", rol: "Tanque, Support", complejidad: 1, atributo: "fuerza" },
    { name: "Primal Beast", img: "img/heroes/primal_beast.png", rol: "Tanque, Mid", complejidad: 1, atributo: "fuerza" },
    { name: "Pudge", img: "img/heroes/pudge.png", rol: "Iniciador", complejidad: 2, atributo: "fuerza" },
    { name: "Slardar", img: "img/heroes/slardar.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Spirit Breaker", img: "img/heroes/spirit_breaker.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Sven", img: "img/heroes/sven.png", rol: "Carry", complejidad: 1, atributo: "fuerza" },
    { name: "Tidehunter", img: "img/heroes/tidehunter.png", rol: "Tanque, Iniciador", complejidad: 2, atributo: "fuerza" },
    { name: "Timbersaw", img: "img/heroes/shredder.png", rol: "Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Tiny", img: "img/heroes/tiny.png", rol: "Iniciador", complejidad: 2, atributo: "fuerza" },
    { name: "Treant Protector", img: "img/heroes/treant.png", rol: "Support", complejidad: 1, atributo: "fuerza" },
    { name: "Tusk", img: "img/heroes/tusk.png", rol: "Iniciador", complejidad: 2, atributo: "fuerza" },
    { name: "Underlord", img: "img/heroes/abyssal_underlord.png", rol: "Tanque", complejidad: 2, atributo: "fuerza" },
    { name: "Undying", img: "img/heroes/undying.png", rol: "Support, Tanque", complejidad: 1, atributo: "fuerza" },
    { name: "Wraith King", img: "img/heroes/skeleton_king.png", rol: "Carry, Tanque", complejidad: 1, atributo: "fuerza" },
    { name: "Anti-Mage", img: "img/heroes/antimage.png", rol: "Carry", complejidad: 1, atributo: "agilidad" },
    { name: "Arc Warden", img: "img/heroes/arc_warden.png", rol: "Mid, Carry", complejidad: 3, atributo: "agilidad" },
    { name: "Bloodseeker", img: "img/heroes/bloodseeker.png", rol: "Mid, Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Bounty Hunter", img: "img/heroes/bounty_hunter.png", rol: "Support, Mid", complejidad: 2, atributo: "agilidad" },
    { name: "Clinkz", img: "img/heroes/clinkz.png", rol: "Mid, Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Drow Ranger", img: "img/heroes/drow_ranger.png", rol: "Carry, Mid", complejidad: 1, atributo: "agilidad" },
    { name: "Ember Spirit", img: "img/heroes/ember_spirit.png", rol: "Mid", complejidad: 2, atributo: "agilidad" },
    { name: "Faceless Void", img: "img/heroes/faceless_void.png", rol: "Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Gyrocopter", img: "img/heroes/gyrocopter.png", rol: "Mid, Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Hoodwink", img: "img/heroes/hoodwink.png", rol: "Iniciador, Support", complejidad: 2, atributo: "agilidad" },
    { name: "Juggernaut", img: "img/heroes/juggernaut.png", rol: "Carry", complejidad: 1, atributo: "agilidad" },
    { name: "Luna", img: "img/heroes/luna.png", rol: "Carry", complejidad: 1, atributo: "agilidad" },
    { name: "Medusa", img: "img/heroes/medusa.png", rol: "Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Meepo", img: "img/heroes/meepo.png", rol: "Carry, Mid", complejidad: 3, atributo: "agilidad" },
    { name: "Monkey King", img: "img/heroes/monkey_king.png", rol: "Carry, Mid", complejidad: 2, atributo: "agilidad" },
    { name: "Morphling", img: "img/heroes/morphling.png", rol: "Carry, Mid", complejidad: 2, atributo: "agilidad" },
    { name: "Naga Siren", img: "img/heroes/naga_siren.png", rol: "Carry, Mid", complejidad: 2, atributo: "agilidad" },
    { name: "Phantom Assassin", img: "img/heroes/phantom_assassin.png", rol: "Carry", complejidad: 1, atributo: "agilidad" },
    { name: "Phantom Lancer", img: "img/heroes/phantom_lancer.png", rol: "Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Razor", img: "img/heroes/razor.png", rol: "Mid, Carry", complejidad: 1, atributo: "agilidad" },
    { name: "Riki", img: "img/heroes/riki.png", rol: "Carry, Support", complejidad: 1, atributo: "agilidad" },
    { name: "Shadow Fiend", img: "img/heroes/nevermore.png", rol: "Mid", complejidad: 1, atributo: "agilidad" },
    { name: "Slark", img: "img/heroes/slark.png", rol: "Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Sniper", img: "img/heroes/sniper.png", rol: "Mid, Carry", complejidad: 1, atributo: "agilidad" },
    { name: "Spectre", img: "img/heroes/spectre.png", rol: "Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Templar Assassin", img: "img/heroes/templar_assassin.png", rol: "Carry, Mid", complejidad: 2, atributo: "agilidad" },
    { name: "Terrorblade", img: "img/heroes/terrorblade.png", rol: "Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Troll Warlord", img: "img/heroes/troll_warlord.png", rol: "Carry, Mid", complejidad: 1, atributo: "agilidad" },
    { name: "Ursa", img: "img/heroes/ursa.png", rol: "Carry", complejidad: 1, atributo: "agilidad" },
    { name: "Viper", img: "img/heroes/viper.png", rol: "Mid", complejidad: 1, atributo: "agilidad" },
    { name: "Weaver", img: "img/heroes/weaver.png", rol: "Carry", complejidad: 2, atributo: "agilidad" },
    { name: "Ancient Apparition", img: "img/heroes/ancient_apparition.png", rol: "Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Crystal Maiden", img: "img/heroes/crystal_maiden.png", rol: "Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Death Prophet", img: "img/heroes/death_prophet.png", rol: "Mid, Pusher", complejidad: 2, atributo: "inteligencia" },
    { name: "Disruptor", img: "img/heroes/disruptor.png", rol: "Support, Iniciador", complejidad: 1, atributo: "inteligencia" },
    { name: "Enchantress", img: "img/heroes/enchantress.png", rol: "Support", complejidad: 2, atributo: "inteligencia" },
    { name: "Grimstroke", img: "img/heroes/grimstroke.png", rol: "Support", complejidad: 2, atributo: "inteligencia" },
    { name: "Jakiro", img: "img/heroes/jakiro.png", rol: "Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Keeper of the Light", img: "img/heroes/keeper_of_the_light.png", rol: "Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Leshrac", img: "img/heroes/leshrac.png", rol: "Mid", complejidad: 2, atributo: "inteligencia" },
    { name: "Lich", img: "img/heroes/lich.png", rol: "Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Lina", img: "img/heroes/lina.png", rol: "Mid, Support", complejidad: 2, atributo: "inteligencia" },
    { name: "Lion", img: "img/heroes/lion.png", rol: "Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Muerta", img: "img/heroes/muerta.png", rol: "Carry, Mid", complejidad: 2, atributo: "inteligencia" },
    { name: "Nature's Prophet", img: "img/heroes/furion.png", rol: "Pusher, Mid", complejidad: 2, atributo: "inteligencia" },
    { name: "Necrophos", img: "img/heroes/necrolyte.png", rol: "Support, Mid", complejidad: 1, atributo: "inteligencia" },
    { name: "Ogre Magi", img: "img/heroes/ogre_magi.png", rol: "Support, Iniciador", complejidad: 1, atributo: "inteligencia" },
    { name: "Oracle", img: "img/heroes/oracle.png", rol: "Support", complejidad: 2, atributo: "inteligencia" },
    { name: "Outworld Destroyer", img: "img/heroes/obsidian_destroyer.png", rol: "Mid", complejidad: 2, atributo: "inteligencia" },
    { name: "Pugna", img: "img/heroes/pugna.png", rol: "Mid, Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Queen of Pain", img: "img/heroes/queenofpain.png", rol: "Mid", complejidad: 1, atributo: "inteligencia" },
    { name: "Rubick", img: "img/heroes/rubick.png", rol: "Support, Mid", complejidad: 2, atributo: "inteligencia" },
    { name: "Shadow Demon", img: "img/heroes/shadow_demon.png", rol: "Support", complejidad: 2, atributo: "inteligencia" },
    { name: "Shadow Shaman", img: "img/heroes/shadow_shaman.png", rol: "Support, Pusher", complejidad: 1, atributo: "inteligencia" },
    { name: "Silencer", img: "img/heroes/silencer.png", rol: "Support, Mid", complejidad: 1, atributo: "inteligencia" },
    { name: "Skywrath Mage", img: "img/heroes/skywrath_mage.png", rol: "Support", complejidad: 2, atributo: "inteligencia" },
    { name: "Storm Spirit", img: "img/heroes/storm_spirit.png", rol: "Mid", complejidad: 2, atributo: "inteligencia" },
    { name: "Tinker", img: "img/heroes/tinker.png", rol: "Mid", complejidad: 2, atributo: "inteligencia" },
    { name: "Warlock", img: "img/heroes/warlock.png", rol: "Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Witch Doctor", img: "img/heroes/witch_doctor.png", rol: "Support", complejidad: 1, atributo: "inteligencia" },
    { name: "Zeus", img: "img/heroes/zuus.png", rol: "Mid", complejidad: 1, atributo: "inteligencia" },
    { name: "Abaddon", img: "img/heroes/abaddon.png", rol: "Support, Tanque", complejidad: 1, atributo: "universal" },
    { name: "Bane", img: "img/heroes/bane.png", rol: "Support", complejidad: 2, atributo: "universal" },
    { name: "Batrider", img: "img/heroes/batrider.png", rol: "Iniciador", complejidad: 2, atributo: "universal" },
    { name: "Beastmaster", img: "img/heroes/beastmaster.png", rol: "Pusher, Tanque, Iniciador", complejidad: 2, atributo: "universal" },
    { name: "Brewmaster", img: "img/heroes/brewmaster.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "universal" },
    { name: "Broodmother", img: "img/heroes/broodmother.png", rol: "Pusher, Iniciador", complejidad: 3, atributo: "universal" },
    { name: "Chen", img: "img/heroes/chen.png", rol: "Support, Pusher", complejidad: 3, atributo: "universal" },
    { name: "Clockwerk", img: "img/heroes/rattletrap.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "universal" },
    { name: "Dark Seer", img: "img/heroes/dark_seer.png", rol: "Iniciador", complejidad: 2, atributo: "universal" },
    { name: "Dark Willow", img: "img/heroes/dark_willow.png", rol: "Support", complejidad: 2, atributo: "universal" },
    { name: "Lycan", img: "img/heroes/lycan.png", rol: "Pusher, Tanque", complejidad: 2, atributo: "universal" },
    { name: "Dazzle", img: "img/heroes/dazzle.png", rol: "Support", complejidad: 1, atributo: "universal" },
    { name: "Enigma", img: "img/heroes/enigma.png", rol: "Iniciador, Pusher", complejidad: 2, atributo: "universal" },
    { name: "Invoker", img: "img/heroes/invoker.png", rol: "Mid, Iniciador", complejidad: 3, atributo: "universal" },
    { name: "Io", img: "img/heroes/wisp.png", rol: "Support", complejidad: 3, atributo: "universal" },
    { name: "Lone Druid", img: "img/heroes/lone_druid.png", rol: "Pusher, Mid, Carry", complejidad: 3, atributo: "universal" },
    { name: "Magnus", img: "img/heroes/magnataur.png", rol: "Iniciador, Mid", complejidad: 2, atributo: "universal" },
    { name: "Mars", img: "img/heroes/mars.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "universal" },
    { name: "Mirana", img: "img/heroes/mirana.png", rol: "Support, Iniciador", complejidad: 2, atributo: "universal" },
    { name: "Nyx Assassin", img: "img/heroes/nyx_assassin.png", rol: "Iniciador, Support", complejidad: 2, atributo: "universal" },
    { name: "Pangolier", img: "img/heroes/pangolier.png", rol: "Iniciador", complejidad: 3, atributo: "universal" },
    { name: "Phoenix", img: "img/heroes/phoenix.png", rol: "Support, Tanque", complejidad: 2, atributo: "universal" },
    { name: "Sand King", img: "img/heroes/sand_king.png", rol: "Iniciador, Tanque", complejidad: 2, atributo: "universal" },
    { name: "Snapfire", img: "img/heroes/snapfire.png", rol: "Support, Iniciador", complejidad: 2, atributo: "universal" },
    { name: "Techies", img: "img/heroes/techies.png", rol: "Support, Iniciador", complejidad: 3, atributo: "universal" },
    { name: "Vengeful Spirit", img: "img/heroes/vengefulspirit.png", rol: "Support, Iniciador", complejidad: 1, atributo: "universal" },
    { name: "Venomancer", img: "img/heroes/venomancer.png", rol: "Support, Iniciador, Pusher", complejidad: 1, atributo: "universal" },
    { name: "Visage", img: "img/heroes/visage.png", rol: "Mid", complejidad: 3, atributo: "universal" },
    { name: "Windranger", img: "img/heroes/windrunner.png", rol: "Mid, Support", complejidad: 2, atributo: "universal" },
    { name: "Winter Wyvern", img: "img/heroes/winter_wyvern.png", rol: "Support", complejidad: 2, atributo: "universal" },
    { name: "Void Spirit", img: "img/heroes/void_spirit.png", rol: "Mid, Iniciador", complejidad: 3, atributo: "universal" }
];

/* export { heroes }; */


